<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-10" name="com.focus.testcases.MasterAuthorizationTest" tests="16" failures="2" timestamp="3 Jan 2023 14:38:02 GMT" time="282.173" errors="0">
  <testcase name="checkEditingMasterAuthorization" time="26.772" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkDeleteInWarehouseInWarehouseMaster" time="16.832" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkShowAllUnAuthorizeOptionInAccountsMasterPage" time="8.479" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkDeletingMasterAuthorization" time="15.220" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkLogoutAndLoginWithSUAfterWarehouseAuthorization" time="12.382" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkLogoutAndLoginWithUserAllOptions" time="12.295" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkCreatingDemoWarehouseAndTrialWarehouse" time="15.686" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkVerifyingWarehouseCreated" time="18.094" classname="com.focus.testcases.MasterAuthorizationTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.MasterAuthorizationTest.checkVerifyingWarehouseCreated(MasterAuthorizationTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkVerifyingWarehouseCreated -->
  <testcase name="checkValidatingAndAuthorizingWarehouseForAuthorization" time="12.180" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkLogoutAndLoginWithSU" time="12.255" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkLogoutAndLoginWithUserAllOptionsForWarehouseAuthorization" time="12.288" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkVerifyingWarehouseCreatedAfterAuthorization" time="32.133" classname="com.focus.testcases.MasterAuthorizationTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.MasterAuthorizationTest.checkVerifyingWarehouseCreatedAfterAuthorization(MasterAuthorizationTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkVerifyingWarehouseCreatedAfterAuthorization -->
  <testcase name="checkValidatingAndAuthorizingTrialWarehouse" time="12.303" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkVerifyingWarehouseInPurchaseVoucherAfterAuthorization" time="18.117" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkSavingMasterAuthorization" time="31.919" classname="com.focus.testcases.MasterAuthorizationTest"/>
  <testcase name="checkCreatingWarehouseFromVoucherLevelAndValidatingWarehouseList" time="25.218" classname="com.focus.testcases.MasterAuthorizationTest"/>
</testsuite> <!-- com.focus.testcases.MasterAuthorizationTest -->
