<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-10" name="com.focus.testcases.ConfigureMasterTest" tests="10" failures="1" timestamp="30 Dec 2022 15:39:00 GMT" time="110.446" errors="0">
  <testcase name="checkSavedMasterAndUpdatingTheMaster" time="3.376" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkDeletingSavedGroupmasterWithChildmaster" time="4.607" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkUpdatedMasterAndDeleteThatMaster" time="12.765" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkAddingGroupMasterInConfigureMaster" time="18.303" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkAddingChildMasterInGroupMaster" time="8.434" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkAddingGroupMasterForDeletion" time="15.561" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkconfigureMasters" time="8.960" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkSavingMasterInConfigureMaster" time="13.399" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkSavingMasterForRecordCreation" time="13.324" classname="com.focus.testcases.ConfigureMasterTest"/>
  <testcase name="checkSavedMaserInMastersListAndSaveRecord" time="11.717" classname="com.focus.testcases.ConfigureMasterTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.ConfigureMasterTest.checkSavedMaserInMastersListAndSaveRecord(ConfigureMasterTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavedMaserInMastersListAndSaveRecord -->
</testsuite> <!-- com.focus.testcases.ConfigureMasterTest -->
