<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-10" name="com.focus.testcases.PDCTest" tests="34" failures="4" timestamp="4 Jan 2023 06:58:19 GMT" time="439.850" errors="0">
  <testcase name="checkCreationOfNewCashAndBankAccountType" time="32.110" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkConvertingPDPVoucherInPDCScreenAfterExtraField" time="15.997" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkConvertMaturedPDCScreenForPDPVAT" time="14.776" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkConvertingVouchersPDPInPDCVoucherScreenWithOutPostOnDate" time="0.411" classname="com.focus.testcases.PDCTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PDCTest.checkConvertingVouchersPDPInPDCVoucherScreenWithOutPostOnDate(PDCTest.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkConvertingVouchersPDPInPDCVoucherScreenWithOutPostOnDate -->
  <testcase name="checkSavingVoucherInPDPVATWithVendorB" time="26.606" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkAddExtraFieldPDCInHeaderFieldOFPayments" time="24.218" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkCovertingVoucherInPDC" time="15.872" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkUpdateinPDCUnderSettingMenuForEnableReversePostingInRecepits" time="4.237" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkSavingVoucherToPostDatedReceipts" time="29.339" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkPDCOptionsUnderSettings" time="4.807" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkConvertedMaturePDCScreenWithNoPDCExists" time="18.190" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkSavingVoucherInPostDatedReceiptsWithCustomerC" time="8.582" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkSavedCovertedVoucherInReceiptsAfterReversePosting" time="17.181" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkDeleteOptionInPDPVAT" time="1.101" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkSavingNewVoucherInPDPVATOnFutureDateWithCurrencyAEDAndDepartmentINDIA" time="33.955" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkDeleteOptionInPDRVAT" time="1.146" classname="com.focus.testcases.PDCTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PDCTest.checkDeleteOptionInPDRVAT(PDCTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkDeleteOptionInPDRVAT -->
  <testcase name="checkCovertingVoucherInPDCWithReversePosting" time="15.116" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkCovertingPDPVoucherInPDCWithReversePosting" time="17.707" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkUpdateinPDCUnderSettingMenuForDisableEnableReversePostingInRecepits" time="4.520" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkClickOnConvertedPDCVouchersAfterDeletionOfConvertedVoucherInRecepits" time="12.426" classname="com.focus.testcases.PDCTest"/>
  <testcase name="CheckSavedVoucherInPDPVATInCovertedPDCScreen" time="12.078" classname="com.focus.testcases.PDCTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PDCTest.CheckSavedVoucherInPDPVATInCovertedPDCScreen(PDCTest.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckSavedVoucherInPDPVATInCovertedPDCScreen -->
  <testcase name="checkSavedVoucherInPDRVAT" time="1.617" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkConvertedPDCVoucherInPayments" time="12.164" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkConvertingVouchersInPDCVoucherScreenWithOutPostOnDate" time="0.410" classname="com.focus.testcases.PDCTest"/>
  <testcase name="CheckSavingVoucherInPDPVAT" time="29.201" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkUpdateinPDCUnderSettingMenuForEnableReversePostingInPayments" time="2.639" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkSavedCovertedVoucherInPaymentsAfterReversePosting" time="12.496" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkSavedVouchersInPDCVoucherScreenWithOutPostOnDate" time="14.864" classname="com.focus.testcases.PDCTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PDCTest.checkSavedVouchersInPDCVoucherScreenWithOutPostOnDate(PDCTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavedVouchersInPDCVoucherScreenWithOutPostOnDate -->
  <testcase name="checkEditingVoucherAndSavingInPDRVAT" time="8.580" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkConvertedPDCVoucherInReceipts" time="12.217" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkEditingVoucherAndSavingInPDPVAT" time="3.524" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkDeleteOfConvertedVoucherinRecepits" time="0.879" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkSavedVoucherInPDPVAT" time="1.548" classname="com.focus.testcases.PDCTest"/>
  <testcase name="checkAddExtraFieldPDCInHeaderFieldOFReceipts" time="29.336" classname="com.focus.testcases.PDCTest"/>
</testsuite> <!-- com.focus.testcases.PDCTest -->
